---
title: "Single case"
output: html_document
date: "2024-01-06"
---

```{r}
library(MASS)
library(lme4)
library(nlme)
library(tidyverse)
library(parallel)
library(doParallel)
library(foreach)
library(gee)
```

```{r}
# Parallel running
if (length(showConnections()) > 0) closeAllConnections()
ncores=detectCores()
cl <- makeCluster(ncores)  
registerDoParallel(cl)
```


```{r setup, include=FALSE} 
#knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
# Correlation structure
# Exchangeable
exch_cor <- function(n, sigma, rho){
  covmat <- rho * outer(sigma, sigma, `*`)
  diag(covmat) <- sigma^2
  return(covmat)
}

# AR1
ar1_cor <- function(n, sigma, rho){
  rhomat <- rho^abs(outer(1:n, 1:n, `-`))
  covmat <- rhomat*outer(sigma, sigma, `*`)
  diag(covmat) <- sigma^2
  return(covmat)
}

# Correlation term (alpha3)
corr_term = function(numer,denom){
  return(numer/denom)
}

# Convert data to long (full) configuration
# Scale baseline value and center time
convert_long = function(id, time1, y, p){
  datay = data.frame(id, time1, y)
  y1 = rep(datay[datay$time1==0,]$y, each=p)

  ydata_long = datay %>% 
    mutate(y1=y1) %>% 
    mutate(y.1 = scale(y1)[,1]) %>% 
    mutate(timec = time1 - mean(time1))
  return(ydata_long)
}
```

# For Reference Scenario (Scenario 1)
```{r}
# Fixed effect `alpha` in equation 3.1.
alpha_t = c(55,4)
alpha_c = c(55,2)

# Covariance matrix `D` of random effect `b` in equation 3.1.
sigma_int_t = 5.5
sigma_int_c = 5.5
sigma_time1_t = 3.5
sigma_time1_c = 3.5
corr_t = 0.3
corr_c = 0.5
D_t = matrix(c(sigma_int_t^2, corr_t*sigma_int_t*sigma_time1_t, corr_t*sigma_int_t*sigma_time1_t, sigma_time1_t^2), nrow=2)
D_c = matrix(c(sigma_int_c^2, corr_c*sigma_int_c*sigma_time1_c, corr_c*sigma_int_c*sigma_time1_c, sigma_time1_c^2), nrow=2)

# Get k directly from model parameters (k2)
k2 = (corr_c*sigma_time1_c)/(corr_t*sigma_time1_t)

# Covariance matrix `R` of residuals `e` in equation 3.1.
p=3
sd_t <- rep(2,p)
rho_t <- 0.3
sd_c = rep(2,p)
rho_c = 0.3
R_t=ar1_cor(p,sd_t,rho_t)
R_c=ar1_cor(p,sd_c,rho_c)
```

# Single group (linear model with gee)
```{r}
n=1000 # Sample size

id = rep(1:n, each=p)
time1 = rep((0:(p-1)),n)
tx=rep(c(1,0), each=(p*n)) # Treatment indicator (1: Treatment, 0: Control)

Zt = mvrnorm(n, c(0,0), D_t)
b0it=Zt[,1] # Random intercepts in treatment group 
b1it=Zt[,2] # Random slopes in treatment group
  
Zc = mvrnorm(n, c(0,0), D_c)
b0ic=Zc[,1] # Random intercepts in control group
b1ic=Zc[,2] # Random slopes in control group

epsilon_t = mvrnorm(n, rep(0,p), R_t) # Residuals in treatment group
epsilon_c = mvrnorm(n, rep(0,p), R_c) # Residuals in control group

# Create response values for treatment and control group  
yt = (alpha_t[1]+b0it[id]) + (alpha_t[2]+b1it[id])*time1 + c(t(epsilon_t))
yc = (alpha_c[1]+b0ic[id]) + (alpha_c[2]+b1ic[id])*time1 + c(t(epsilon_c))

# Convert data to long (full) configuration for treatment and control group
ydata_long = convert_long(id,time1,yt,p)
ydata_long0 = convert_long(id,time1,yc,p)

# Combine data from treatment and control group
ytotal = rbind(ydata_long, ydata_long0)

# Add treatment indicator variable
ytotal2 = cbind(ytotal,tx)

# Get naive estimate
mod.naive = gee(y~timec*y.1, data=ydata_long, id=id, corstr = "AR-M", Mv=1)
beta.naive=coef(mod.naive)[4]

# Get RCT estimate
mod.rct =  gee(y~timec*y.1*tx, data=ytotal2, id=id, corstr = "AR-M", Mv=1)
beta.rct = coef(mod.rct)[8]

# Create Y_1*T variable in equation 2.14 for treatment group
ydata_long1 = ydata_long %>% mutate(y1_t =y.1*timec)
cov_mat_trt = cov(ydata_long1)

# Create Y_1*T variable in equation 2.14 for control group
ydata_long01 = ydata_long0 %>% mutate(y1_t =y.1*timec)
cov_mat_cont = cov(ydata_long01)

# Estimate true k value (k1)
k1 = cov_mat_cont["y1_t", "y"]/cov_mat_trt["y1_t", "y"]

c(k1,k2)

```

```{r}
# Calculate correction term (alpha3) using k1
alpha3_1 = corr_term(numer=k1*cov_mat_trt["y1_t", "y"], denom=cov_mat_trt["y1_t", "y1_t"])

# Calculate correction term (alpha3) using k2
alpha3_2 = corr_term(numer=k2*cov_mat_trt["y1_t", "y"], denom=cov_mat_trt["y1_t", "y1_t"])
```

```{r}
# Get corrected estimates
beta.cor_1 = beta.naive-alpha3_1
beta.cor_2 = beta.naive-alpha3_2

# Naive estimate, RCT estimate, Corrected estimate using Approach 1 and 2
c(beta.naive, beta.rct, beta.cor_1, beta.cor_2)
```








`

